---
- name: Setup before gathering facts
  hosts: servers
  gather_facts: no

  roles:
    - setup

- name: Setup Servers
  hosts: servers

  roles:
    - rails-config
    - rbenv
    - nodenv
    - pyenv
    - nginx
    - mysql
    - postgres
    - docker-ce
