---
- name: Setup before gathering facts
  hosts: servers
  gather_facts: no

  roles:
    - setup

- name: Setup Servers
  hosts: servers

  roles:
    - rails
    - rbenv
    - nodenv
    - pyenv
    - nginx
#    - passenger
    - mysql
