---
- hosts: servers
  remote_user: vagrant

  tasks:
    - include: 'tasks/pretasks.yml'
    - include: 'tasks/install_pyenv_ubuntu.yml'
      vars:
        remote_user: vagrant
        pyenv_url: https://github.com/yyuu/pyenv.git
        pyenv_path: '/home/{{ remote_user }}/.pyenv'
        python_version: 2.7.13