---
- name: Test prod
  hosts: servers
  gather_facts: no

  tasks:

    - debug:
        var: "{{ item }}"
      with_items:
        - remote_user
        - deploy_user
        - ruby_version
        - node_version
        - app_name
        - app_env
