- name: 'install dependencies'
  apt: name={{item}} state=installed
  with_items:
      - git
      - gcc
      - libssl-dev 
      - libreadline-dev
      - zlib1g-dev
      - build-essential
      - checkinstall
      - tk-dev
      - libbz2-dev
  become: true
  become_method: sudo
- shell: 'ls {{ pyenv_path }}/versions | grep {{ python_version }}'
  register: check_python
  ignore_errors: yes
- name: 'clone pyenv'
  git: repo={{ pyenv_url }} dest={{ pyenv_path }} accept_hostkey=yes
- name: Add pyenv to PATH
  lineinfile: 
    dest: /home/{{ remote_user }}/.bash_profile
    regexp: '^export.*pyenv/bin'
    line: export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"    
- name: Install pyenv shims
  lineinfile: 
    dest: /home/{{ remote_user }}/.bash_profile
    regexp: '^eval.*pyenv init'
    line: 'eval "$(pyenv init -)"'
- name: 'install python {{ python_version }}'
  shell: '{{ pyenv_path }}/bin/pyenv install {{ python_version }}'
  when: check_python.stdout != python_version
- name: 'rehash python installations'
  shell: '{{ pyenv_path }}/bin/pyenv rehash'
  when: check_python.stdout != python_version
- name: 'set default python {{ python_version }}'
  shell: '{{ pyenv_path }}/bin/pyenv global {{ python_version }}'
