- name: Create deployment user
  user: name={{ deploy_user }} comment="Application deployment user"
  become: true

- name: Create deployment directory
  file: >
    path={{deploy_directory}} 
    owner={{ deploy_user }}
    group={{ deploy_user }}
    state=directory
  become: true

- name: Make shared directories
  file: >
    path={{deploy_directory}}/shared/{{item}} 
    group={{ deploy_user }}
    owner={{ deploy_user }}
    state=directory
  with_items:
    - tmp
    - tmp/pids
    - tmp/puma
    - log
    - public
    - bundle
    - bin
    - config
    - config/puma
  tags: shared
  become: true

- name: Create database.yml
  template: >
    src=database.yml.j2 
    dest={{deploy_directory}}/shared/config/database.yml 
    force=yes mode=755 owner={{ deploy_user }}
  become: true
