- name: Create deployment user
  user: name={{ deploy_user }} comment="Application deployment user"
  become: true

- name: Create deployment directory
  file: >
    path={{deploy_directory}} 
    owner={{ deploy_user }}
    group={{ deploy_user }}
    state=directory
  become: true
