- name: Create deployment user
  user: name=deploy comment="Application deployment user"

- name: Create deployment directory
  file: >
    path={{deploy_directory}} 
    owner=deploy 
    group=deploy 
    state=directory

- name: Make shared directories
  file: >
    path={{deploy_directory}}/shared/{{item}} 
    group=deploy 
    owner=deploy 
    state=directory
  with_items:
    - tmp
    - tmp/pids
    - tmp/puma
    - log
    - public
    - bundle
    - bin
    - config
    - config/puma
  tags: shared

- name: Create database.yml
  template: >
    src=database.yml.j2 
    dest={{deploy_directory}}/shared/config/database.yml 
    force=yes mode=755 owner=deploy

- name: Install Bundler
  command: gem install bundler
