---
- name: Check for {{ node_version }}
  stat:
    path: '{{ nodenv_path }}/versions/{{ node_version }}'
  register: node
  ignore_errors: yes

- block:
  - name: Install node {{ node_version }}
    shell: 'NODENV_ROOT={{ nodenv_path }} {{ nodenv_path }}/bin/nodenv install {{ node_version }}'
    become: true

  - name: Rehash node installations
    shell: 'NODENV_ROOT={{ nodenv_path }} {{ nodenv_path }}/bin/nodenv rehash'
    become: true

  - name: Set default node {{ node_version }}
    shell: 'NODENV_ROOT={{ nodenv_path }} {{ nodenv_path }}/bin/nodenv global {{ node_version }}'
    become: true

  - name: Add nodenv to PATH
    template:
      src: nodenv.sh.j2
      dest: /etc/profile.d/nodenv.sh
      mode: a+x
    become: true

  when: node.stat.exists == false