- name: Clone nodenv
  git:
    repo: '{{ nodenv_url }}'
    dest: '{{ nodenv_path }}'
    accept_hostkey: yes
  when: nodenv_exists.stdout != "true"

- name: Compile dynamic bash extension to speed up nodenv
  shell: '{{ nodenv_path }}/src/configure && make -C {{ nodenv_path }}/src'
  when: nodenv_exists.stdout != "true"

- name: Clone node-build
  git:
    repo: '{{ node_build_url }}'
    dest: '{{ node_build_path }}'
  when: nodenv_exists.stdout != "true"