---
- include: dependencies/debian.yml
  when: ansible_os_family == 'Debian'

- include: dependencies/centos.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- include: install-nodenv.yml

- include: install-node.yml
