- name: Determine release
  shell: "lsb_release -a 2>/dev/null | grep Codename | awk '{print $2}'"
  register: release
  ignore_errors: yes

- debug:
    var: release

- name: Install python2 for xenial
  apt: name='python-simplejson' state=installed update_cache=yes cache_valid_time=3600
  when: release.stdout == 'xenial'

