- name: Check for previous installation
  shell: '[ -d {{ nodenv_path }} ] && [ -d {{ node_build_path }} ] && echo true'
  ignore_errors: true
  register: nodenv_exists

- name: Install dependencies
  apt: name={{item}} state=installed update_cache=yes cache_valid_time=3600
  with_items:
      - make
      - git
      - gcc
      - libssl-dev 
      - libreadline-dev
      - zlib1g-dev
      - make
  become: true
  when: nodenv_exists.stdout != "true"

- name: Check for {{ node_version }}
  shell: ls {{ nodenv_path }}/versions | grep {{ node_version }}
  register: check_node
  ignore_errors: yes

- name: Clone nodenv
  git: repo={{ nodenv_url }} dest={{ nodenv_path }} accept_hostkey=yes
  when: nodenv_exists.stdout != "true"

- name: Compile dynamic bash extension to speed up nodenv
  shell: cd ~/.nodenv && src/configure && make -C src
  when: nodenv_exists.stdout != "true"

- name: Clone node-build
  git: repo={{ node_build_url }} dest={{ node_build_path }}
  when: nodenv_exists.stdout != "true"

- name: Add nodenv to PATH
  lineinfile: 
    dest: /home/{{ remote_user }}/.profile
    regexp: ^export.*nodenv/bin
    line: export PATH="$HOME/.nodenv/bin:$HOME/.nodenv/shims:$PATH"    

- name: Install nodenv shims
  lineinfile: 
    dest: /home/{{ remote_user }}/.profile
    regexp: ^eval.*nodenv init
    line: eval "$(nodenv init -)"

- name: Install node {{ node_version }}
  shell: '{{ nodenv_path }}/bin/nodenv install {{ node_version }}'
  when: check_node.stdout != node_version

- name: Rehash node installations
  shell: '{{ nodenv_path }}/bin/nodenv rehash'
  when: check_node.stdout != node_version

- name: Set default node {{ node_version }}
  shell: '{{ nodenv_path }}/bin/nodenv global {{ node_version }}'
