- name: install dependencies
  apt: name={{item}} state=installed update_cache=yes cache_valid_time=3600
  with_items:
      - git
      - gcc
      - libssl-dev 
      - libreadline-dev
      - zlib1g-dev
      - make

- shell: ls {{ nodenv_path }}/versions | grep {{ node_version }}
  register: check_node
  ignore_errors: yes

- name: clone nodenv
  git: repo={{ nodenv_url }} dest={{ nodenv_path }} accept_hostkey=yes

- name: compile dynamic bash extension to speed up nodenv
  shell: cd ~/.nodenv && src/configure && make -C src

- name: clone node-build
  git: repo={{ node_build_url }} dest={{ node_build_path }}

- name: Add nodenv to PATH
  lineinfile: 
    dest: /home/{{ remote_user }}/.profile
    regexp: ^export.*nodenv/bin
    line: export PATH="$HOME/.nodenv/bin:$HOME/.nodenv/shims:$PATH"    

- name: Install nodenv shims
  lineinfile: 
    dest: /home/{{ remote_user }}/.profile
    regexp: ^eval.*nodenv init
    line: eval "$(nodenv init -)"

- name: install node {{ node_version }}
  shell: {{ nodenv_path }}/bin/nodenv install {{ node_version }}
  when: check_node.stdout != node_version

- name: rehash node installations
  shell: {{ nodenv_path }}/bin/nodenv rehash
  when: check_node.stdout != node_version

- name: set default node {{ node_version }}
  shell: {{ nodenv_path }}/bin/nodenv global {{ node_version }}
