---
- name: Install python {{ python_version }}
  raw: 'PYENV_ROOT={{ pyenv_path }} {{ pyenv_path }}/bin/pyenv install {{ python_version }}'
  become: true

- name: Rehash python installations
  raw: 'PYENV_ROOT={{ pyenv_path }} {{ pyenv_path }}/bin/pyenv rehash'
  become: true
