- name: Install nginx Debian
  apt: >
    package={{ item }} 
    state=installed 
    force=yes 
    update_cache=yes 
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - nginx
  become: true

- name: Install nginx CentOS
  yum: >
    package={{ item }}
    state=installed
    update_cache=yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"
  with_items:
    - nginx
  become: true

- name: Stat index
  stat: path={{ www_path }}/index.nginx-debian.html
  register: index_stat

- name: Rename index.ubuntu-dedian.html to index.html
  command: mv {{ www_path }}/index.nginx-debian.html {{ www_path }}/index.html
  become: true
  when: index_stat.stat.exists == true

- name: Change owner
  file: >
    dest={{ www_path }}
    state=directory
    owner={{ deploy_user }}
  become: true

- name: Restart nginx
  action: service name=nginx state=restarted
  become: true
