- name: Install nginx
  apt: >
    package={{ item }} 
    state=installed 
    force=yes 
    update_cache=yes 
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - nginx
  become: true

- name: Stat index
  stat: path=/var/www/html/index.nginx-debian.html
  register: index_stat

- name: Rename index.ubuntu-dedian.html to index.html
  command: mv /var/www/html/index.nginx-debian.html /var/www/html/index.html
  become: true
  when: index_stat.stat.exists == true

- name: Change owner
  file: >
    dest=/var/www/html
    state=directory
    owner={{ deploy_user }}
  become: true

- name: Copy nginx configuration
  template: >
    src=default.conf
    dest=/etc/nginx/conf.d/default.conf
  become: true
  notify: restart nginx

# - name: Remove the default app
#   file: >
#     path=/etc/nginx/sites-enabled/default
#     state=absent
#   become: true

- name: Remove the app's config, if exists
  file: >
    path=/etc/nginx/sites-available/default
    state=absent
  become: true

- name: Remove the app's symlink, if exists
  file: >
    path=/etc/nginx/sites-enabled/{{app_name}}
    state=absent
  become: true

- name: Configure nginx for the app
  template: >
    src=etc_nginx_sites-available_app.conf.j2 
    dest=/etc/nginx/sites-available/{{app_name}} 
    group=www-data 
    owner=www-data 
    force=yes
  become: true

- name: Enable the app
  file: >
    src=/etc/nginx/sites-available/{{app_name}} 
    dest=/etc/nginx/sites-enabled/{{app_name}}
    state=link
  become: true
  notify: restart nginx

- name: Restart nginx
  action: service name=nginx state=restarted
  become: true
