- name: Install nginx
  apt: >
    package={{ item }} 
    state=installed 
    force=yes 
    update_cache=yes 
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - nginx
  become: true

# - name: Copy nginx configuration
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   become: true
#   notify: restart nginx

- name: Remove the default app
  command: rm -rf /etc/nginx/sites-enabled/default
  become: true

- name: Remove the app's config, if exists
  command: rm -rf /etc/nginx/sites-enabled/default
  become: true

- name: Remove the app's symlink, if exists
  command: rm -rf /etc/nginx/sites-enabled/{{app_name}}
  become: true

- name: Configure nginx for the app
  template: >
    src=etc_nginx_sites-available_app.conf.j2 
    dest=/etc/nginx/sites-available/{{app_name}} 
    group=www-data 
    owner=www-data 
    force=yes
  become: true

- name: Enable the app
  command: >
    ln -s /etc/nginx/sites-available/{{app_name}} 
    /etc/nginx/sites-enabled/{{app_name}}
  become: true
  notify: restart nginx

- name: Restart nginx
  action: service name=nginx state=restarted
  become: true