- name: Install nginx
  apt: >
    package={{ item }} 
    state=installed 
    force=yes 
    update_cache=yes 
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  with_items:
    - nginx

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  become: true
  notify: restart nginx
