---
- name: Clone rbenv
  git:
    repo: '{{ rbenv_url }}'
    dest: '{{ rbenv_path }}'
    accept_hostkey: yes
  when: rbenv_exists.stdout != "true"

- name: Compile dynamic bash extension to speed up rbenv
  shell: '{{ rbenv_path }}/src/configure && make -C {{ rbenv_path }}/src'
  when: rbenv_exists.stdout != "true"

