---
- name: Install ruby {{ ruby_version }}
  shell: 'rbenv install {{ ruby_version }}'
  when: check_ruby.stdout != ruby_version
  become: true
  become_flags: "-iu {{ remote_user }}"

- name: Rehash ruby installations
  shell: 'rbenv rehash'
  when: check_ruby.stdout != ruby_version
  become: true
  become_flags: "-iu {{ remote_user }}"

- name: Set default ruby {{ ruby_version }}
  shell: 'rbenv global {{ ruby_version }}'
  become: true
  become_flags: "-iu {{ remote_user }}"

