---
- hosts: servers
  sudo: yes
  remote_user: vagrant
  gather_facts: no
  pre_tasks:
    - name: ''
      shell: "lsb_release -a 2>/dev/null | grep Codename | awk '{print $2}'"
      register: release
      ignore_errors: yes
    - name: 'update apt packages list'
      raw: sudo apt-get update
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
      when: release.stdout == 'xenial'
    - name: 'install git'
      raw: sudo apt-get -y install git
    - name: 'install gcc'
      raw: sudo apt-get -y install gcc
    - name: 'install ruby dependencies'
      raw: sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev
  sudo: no

  vars:
    remote_user: vagrant
    rbenv_url: https://github.com/sstephenson/rbenv.git
    rbenv_path: '/home/{{ remote_user }}/.rbenv'
    ruby_build_url: https://github.com/sstephenson/ruby-build.git
    ruby_build_path: '{{ rbenv_path }}/plugins/ruby-build'
    ruby: '{{ rbenv_path }}/shims/ruby'
    ruby_version: 2.2.3
    ruby_path: '{{ rbenv_path }}/versions/{{ ruby_version }}'

  tasks:
    - shell: 'ls {{ rbenv_path }}/versions | grep {{ ruby_version }}'
      register: check_ruby
      ignore_errors: yes
    - name: 'clone rbenv'
      git: repo={{ rbenv_url }} dest={{ rbenv_path }} accept_hostkey=yes
    - name: 'clone ruby-build'
      git: repo={{ ruby_build_url }} dest={{ ruby_build_path }}
    - name: 'update bashrc'
      shell: echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"' \
        >> /home/{{ remote_user }}/.bash_profile && \
        echo 'which rbenv > /dev/null && eval "$(rbenv init -)"' \
        >> /home/{{ remote_user }}/.bash_profile
    - name: 'install ruby {{ ruby_version }}'
      shell: '{{ rbenv_path }}/bin/rbenv install {{ ruby_version }}'
      when: check_ruby.stdout != ruby_version
    - name: 'set default ruby {{ ruby_version }}'
      shell: '{{ rbenv_path }}/bin/rbenv global {{ ruby_version }}'
