---
- hosts: servers
  tasks:
    - name: Installs nginx
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx
      become: true
      become_user: root

  handlers:
    - name: start nginx
      service: name=nginx state=started
