---
- hosts: servers
  remote_user: vagrant
  gather_facts: no
  pre_tasks:
    - name: ''
      become: true
      shell: "lsb_release -a 2>/dev/null | grep Codename | awk '{print $2}'"
      register: release
      ignore_errors: yes
    - name: 'update apt packages list'
      apt:
        update_cache: yes
      become: true
      become_method: sudo
    - name: 'install python2 for xenial'
      become: true
      apt: name='python-simplejson' state=installed
      when: release.stdout == 'xenial'

  vars:
    remote_user: vagrant
    pyenv_url: https://github.com/yyuu/pyenv.git
    pyenv_path: '/home/{{ remote_user }}/.pyenv'
    python_version: 2.7.13

  tasks:
    - name: 'install dependencies'
      apt: name={{item}} state=installed
      with_items:
          - git
          - gcc
          - libssl-dev 
          - libreadline-dev
          - zlib1g-dev
          - build-essential
          - checkinstall
          - tk-dev
          - libbz2-dev
      become: true
      become_method: sudo
    - shell: 'ls {{ pyenv_path }}/versions | grep {{ python_version }}'
      register: check_python
      ignore_errors: yes
    - name: 'clone pyenv'
      git: repo={{ pyenv_url }} dest={{ pyenv_path }} accept_hostkey=yes
    - name: 'update bashrc'
      shell: echo 'export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"' \
        >> /home/{{ remote_user }}/.bash_profile && \
        echo 'which pyenv > /dev/null && eval "$(pyenv init -)"' \
        >> /home/{{ remote_user }}/.bash_profile
    - name: 'install python {{ python_version }}'
      shell: '{{ pyenv_path }}/bin/pyenv install {{ python_version }}'
      when: check_python.stdout != python_version
    - name: 'set default python {{ python_version }}'
      shell: '{{ pyenv_path }}/bin/pyenv global {{ python_version }}'
