---
- name: Install dependencies
  apt:
    name: {{item}}
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
      - make
      - git
      - gcc
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - build-essential
      - checkinstall
      - tk-dev
      - libbz2-dev
  become: true
  when: rvenv_exists.stdout != "true" and ansible_os_family == 'Debian'